### ISSUE TITLE
See the project summary section in README.md to complete the task 

### ISSUE THREAD

**Issue by nets-dev** [Ganapathypinfo/PracticeProject#1]
Thank you for the project. The following is required as one of the basic feature of the project:
_**"Upon selecting a row from the list, the app should re-fetch the list and exclude the user on the selected row. e.g. If a user with id = 3 is selected, exclude this user from fetch result. Subsequently, if a user with id = 1 is selected, exclude only this user (and not the previously selected user with id = 3)"**_

Pay attention to README.md file in the project to finalize the project according to the instructions. 
(Its also advised to commit and push each step of the progress)

Please feel free to ask questions here in the comment section if there is anything unclear. 
We'll keep the review process and we ask you to promptly respond to review comments until the review process is complete.

**Comment by nets-dev** [comment]
@Ganapathypinfo Are you able to continue with this review process?

**Comment by Ganapathypinfo** [comment]
I'm facing recompose issue with simple rest call. Can I use veiwmodel livedata?

**Comment by nets-dev** [comment]
@Ganapathypinfo Yes! You can also leave a more detailed comment here on the recompose issue and we can try to help. 
As long as Jetpack compose is used, using Live Data is acceptable

**Comment by Ganapathypinfo** [comment]
List view I can get selected Item and re-fetch user-List from API and removed selected Item in user-List but that re-feched data not updated with my List UI (Re-Compose not happening). I have done some remember mutablestateof with in my code but after selected item UI not updated.

**Comment by nets-dev** [comment]
Alright, you can leave that if the code for the logic is there and we can discuss it at the end of this review. 
Can you continue with the rest? @Ganapathypinfo 
(If you solve it with Live Data, thats also fine like mentioned above)

**Comment by nets-dev** [comment]
**"It is advised to commit the progress of the task and create a pull request with nets-dev as reviewer when the task is complete."**

@Ganapathypinfo Please commit your progress in small commits and more often. If there is any blocker you face that takes longer than few hours, feel free to reach out here. This review process is meant to be a transparent channel to exchange ideas so please remain active

**Comment by Ganapathypinfo** [comment]
I have implemented View model and Live Data  but  UI not update issue existed.

**Comment by Ganapathypinfo** [comment]
I found **"simulateHotReload(this)"** is doing recompose that its working as expected

**Comment by nets-dev** [comment]
@Ganapathypinfo Thank you for your work so far. We'll discuss this project with you on zoom/teams call next week. But before that, try to accomplish the following in the given order:

- [x] Reply to all the comments under the issue in the Github issues -> **Conversations** tab (https://github.com/Ganapathypinfo/PracticeProject/pull/2). Share your opinion and ask if anything is unclear. 
- [x] Cleanup the project. i.e. remove any unused _**files**_, _**classes**_, **_commented-out/unused code_** and code _**comments**_ that do not offer any more information than the code itself gives. 
- [x] Move on to Task 2 in the README.md file:- **_Write unit tests for the units you see need testing_** 
- [x] Finally if you get time, see Task 4 and prepare to discuss network failure handling. 

Does this sound good? Do you have any question concerning the tasks, comments or this plan? @Ganapathypinfo

**Comment by nets-dev** [comment]
@Ganapathypinfo As we mentioned above, we'd like to discuss with you next week on a zoom/teams call. 
What time suits you best on Tuesday 31.08 for about an hour long discussion? 
(We propose 10:45 - 11:45 or 14 - 15:00 Finnish time but feel free to share what suits you best)

**Comment by Ganapathypinfo** [comment]
Yes we can connect at 10:45 -11:45 on Tuesday

**Comment by nets-dev** [comment]
@Ganapathypinfo Sounds good! We'll give the link here (below) on Tuesday morning latest. Please let us know early if your schedule changes.

**Comment by nets-dev** [comment]
@Ganapathypinfo Here is the meeting link in Teams. If it does not work, we'll send a zoom link so please check here in Github. 
Can you stay active in this comment section tomorrow? 

[Teams meeting link, tomorrow 10:45 - 11:45 Finnish time](https://teams.microsoft.com/l/meetup-join/19%3ameeting_NzZlYWQyODItZWUwNy00ODU0LThmMjEtNGQ2Nzk1MDk0YzQ1%40thread.v2/0?context=%7b%22Tid%22%3a%2279dc228f-c8f2-4016-8bf0-b990b6c72e98%22%2c%22Oid%22%3a%2213eab4a7-c748-4cb4-809e-27977c6812e2%22%7d)

**Comment by Ganapathypinfo** [comment]
I have checked that Teams meeting link, I can connect that Teams link.

**Comment by Ganapathypinfo** [comment]
Hi I'm waiting in the Teams meeting link.

**Comment by nets-dev** [comment]
> Hi I'm waiting in the Teams meeting link.

@Ganapathypinfo The meeting is scheduled 10:45 Finnish time which is 13:15 Indian time. Can you meet us after lunch at the scheduled time?

**Comment by Ganapathypinfo** [comment]
okay fine we can meet at 13:15 Indian time.

**Comment by Ganapathypinfo** [comment]
coed changes done
